volumes:
  db-data:

services:

  db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=wikimedia

    volumes:
      - db-data:/var/lib/postgresql/data